### ISSUE TITLE
error extracting files

### ISSUE THREAD

**Issue by student197** [Aclios/AJT-Tools#1]
hello. I get this error when trying to extract files
![image](https://github.com/Aclios/AJT-Tools/assets/151855986/30c69e93-7330-4c27-96ea-09e04a412c64)

**Comment by Aclios** [comment]
Hello,

As stated in the "Requirements" part, you need to install the Pillow and soundfile modules.
Try to run `python3 -m pip install --upgrade Pillow` and `python3 -m pip install --upgrade soundfile` in a command prompt.

**Comment by student197** [comment]
Thank you. One more question. And how do I make the textures from the switch version look normal?

**Comment by Aclios** [comment]
Well, they are supposed to look normal.
Did you fill correctly the path_init.txt file, with your extracted Switch .pak path as "extracted_switch_pak_path" ?
If so, can you give me one or two samples of the extracted png you get ?

**Comment by student197** [comment]
can you please make the same texture converter for the switch version of the game "ghost trick"?

**Comment by Aclios** [comment]
> can you please make the same texture converter for the switch version of the game "ghost trick"?

The goal of these tools is to work with Apollo Justice Trilogy and I don't plan to expand them to other titles, however you should be able to make it work with few changes: open the _obj/tex/texconverter.py file in a text editor and replace all "tex.719230324" occurrences by "tex.35".

I updated the tools with a new option allowing to export all textures by using the "all" extension, it may be useful for GT.

**Comment by student197** [comment]
Fine. I want to clarify. That is, I just need to replace "tex.719230324" with "tex.35"? And what do I need to do so that the files from ghost trick change during conversion, because the tool is designed for AJT?

**Comment by Aclios** [comment]
Yes, you only need to do that because tex.719230324 and tex.35 seem to be the same format, they are just named differently for some reason.
After doing that, you just need to configure the path_init.txt file with your GT extracted pak folder and "all" as the extension.
Then, you can run the EXTRACT SWITCH.bat file and it should extract the tex files as pngs. 
If you want to create a mod and import new textures, you can just modify some pngs and run IMPORT ALL SWITCH.bat . Though you would probably want to modify these bat files by removing the -msg, -script and -sound options because they won't work for GT.

**Comment by student197** [comment]
![image](https://github.com/Aclios/AJT-Tools/assets/151855986/cd04df84-ef1f-4787-bf5f-c8125d682c
There's something wrong with the textures for the Nintendo switch. What could this be about?

**Comment by student197** [comment]
The textures from apollo justice ace attorney trilogy on the nintendo switch have the same problem

**Comment by student197** [comment]
Why doesn't the "all" command work? For some reason he can't extract some textures
![image](https://github.com/Aclios/AJT-Tools/assets/151855986/b90886d9-c410-48dc-a2fe-6591779b2784)

**Comment by student197** [comment]
I need to transfer the translation from my language from the PC version to the Nintendo Switch. I managed to transfer the text, but the textures did not. :(

**Comment by Aclios** [comment]
> I need to transfer the translation from my language from the PC version to the Nintendo Switch. I managed to transfer the text, but the textures did not. :(

Would it be possible to discuss it on Discord ? It would be much more convenient. My username there is "aclios".
